### ISSUE TITLE
使用缺少东西

### ISSUE THREAD

**Issue by komomon** [idiotc4t/Schrodinger-s-Cat#1]
我按照要求，在linux上装了mingw-w64，但是说mingw不存在
![image](https://user-images.githubusercontent.com/52700174/104397168-284ccd80-5587-11eb-862c-43c4db710f8d.png)

**Comment by idiotc4t** [comment]
把这行代码前面的./llvm-mingw/bin/删掉。
os.system("./llvm-mingw/bin/x86_64-w64-mingw32-gcc -mwindows ./output/temp.cpp -o ./output/%s -static -%s" % (args.output ,args.options))
